menu:
- {name: 'research', url: '/en/research', lang: 'en'}
- {name: 'education', url: '/en/cv', lang: 'en'}
- {name: 'teaching', url: '/en/teaching', lang: 'en'}
- {name: 'recherche', url: '/fr/research', lang: 'fr'}
- {name: 'formation', url: '/fr/cv', lang: 'fr'}
- {name: 'enseignement', url: '/fr/teaching', lang: 'fr'}


contacts:
- {name: 'Bianca Neubert', department: 'Institute for Mathematics', institution: 'Heidelberg University', institution_address: 'INF 205, 69120 Heidelberg, Germany', phone: '+49 6221 54 14185', email: 'neubert@math.uni-heidelberg.de', office: '4/411', image: 'assets/img/contact.jpg'}
